### ISSUE TITLE
RSI Phase I Epic

### ISSUE THREAD

**Issue by RASADSA** [RasaHQ/REI#1]
Phase I

### **Task:**

adapting / writing a bash script which set up KIND in an easy fashion and deploy RASA X via Offical RASA Helmchart

including installing / upgrading helmchart via script.

**Official Supported Platforms:**

- MacOS (Catalina)
- Linux (Debian - based, red hat based, archlinux based)

and it will run on WSL2 (windows) but with no support from RASA

This ticket is treat as an Epic

More information on the setup the why and all the rest:

https://www.notion.so/rasa/Dead-Simple-Installation-and-Upgrade-c04e139bca1b49e689c0c07b86c20ac6?p=1f5a2b652d4543098b43612217b6b686

### **Hardware Requirements:**

**Minimum / Maximum**

- Dual / Quadcore CPU
- 8 GB / 16 GB RAM
- 20 GB / 50 GB Disk

**Software Requirements:**

- homebrew (macos)
- Docker / Docker Desktop
- kubectl
- helm
- KIND

TODOS:

- [x] writing the DSI script 
- [x] Test it under
  - [x] MacOS Catalina
  - [x] Ubuntu 
  - [x] #2
  - [x] Archlinux
- [x] Test Trials with RASA Developers / Infrastructure 
- [x] #3
- [x] #4

trials TODOS:
- [x] #5
- [x] add --verbose flag and silent the clutter of all running actions @tczekajlo @erohmensing @mprazz 
- [x] #6
- [x] clear warning that elaborate sudo and waiting at the step happening
- [x] #7
- [x] #8
   permutation would be a nice slick way to do it
- [x] #9
- [x] make ascii art of RASA Logo infrastructure squad requirement :D
- [x] change KIND nodes from 3 to 1
- [x] #10
- [x] check if kind already is running a rasa cluster
